---
# run this script as: `sudo ansible-playbook jetstream-playbook.yaml`
# run this first: `sudo ansible-galaxy install cmprescott.chrome`


- hosts: localhost
  roles:
     - { role: cmprescott.chrome, become: yes }
  tasks:
    # Check if user permissions for passwordless sudo are set up correctly:
    - lineinfile:
        path: /etc/sudoers.d/90-cloud-init-users
        line: "%admin ALL=(ALL) NOPASSWD:ALL"

    - lineinfile:
        path: /etc/sudoers.d/90-cloudimg-ubuntu
        line: "%admin ALL=(ALL) NOPASSWD:ALL"

    # Set up users and groups:
    - user:
        name: jhaber
        uid: 1000
        comment: "Jaren Haber"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: bradafza
        uid: 1001
        comment: "Brad Afzali"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: harshayu
        uid: 1002
        comment: "Harshayu Girase"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: sujaksh
        uid: 1003
        comment: "Akshat Gokhale"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: arjuns
        uid: 1004
        comment: "Arjun Srinivasan"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: aculich
        uid: 1005
        comment: "Aaron Culich"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: maxyuan
        uid: 1006
        comment: "Max Yuan"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: jiahuazou
        uid: 1007
        comment: "Jiahua Zou"
        groups: users,admin,docker
        shell: /bin/bash
    - user:
        name: serenajiang
        uid: 1008
        comment: "Serena Jiang"
        groups: users,admin,docker
        shell: /bin/bash


#    - name: Set authorized key took from url
    - authorized_key:
        user: jhaber
        state: present
        key: https://github.com/jhaber-zz.keys
    - authorized_key:
        user: bradafza
        state: present
        key: https://github.com/bradafzali.keys
    - authorized_key:
        user: arjuns
        state: present
        key: https://github.com/arjunsrinivasan1997.keys
    - authorized_key:
        user: harshayu
        state: present
        key: https://github.com/HarshayuGirase.keys
    - authorized_key:
        user: sujaksh
        state: present
        key: https://github.com/ajgokhale.keys
    - authorized_key:
        user: aculich
        state: present
        key: https://github.com/aculich.keys
    - authorized_key:
        user: maxyuan
        state: present
        key: https://github.com/MaxYuan85.keys
    - authorized_key:
        user: jiahuazou
        state: present
        key: https://github.com/JiahuaZou.keys
    - authorized_key:
        user: serenajiang
        state: present
        key: https://github.com/serenajiang.keys

    - copy:
        src: charter-school-notebook-server
        dest: /usr/local/bin/charter-school-notebook-server
        owner: root
        group: root
        mode: 0755
